# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: D:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.srcs/sources_1/bd/design_1/design_1.bd
# Block Designs: The module: 'design_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: D:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_99M_0/design_1_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_99M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_99M_0} -quiet] -quiet

# IP: D:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.srcs/sources_1/bd/design_1/ip/design_1_axi_interconnect_0_1/design_1_axi_interconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_1 || ORIG_REF_NAME==design_1_axi_interconnect_0_1} -quiet] -quiet

# IP: D:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.srcs/sources_1/bd/design_1/ip/design_1_riscv_soc_axi_wrapper_0_1/design_1_riscv_soc_axi_wrapper_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_riscv_soc_axi_wrapper_0_1 || ORIG_REF_NAME==design_1_riscv_soc_axi_wrapper_0_1} -quiet] -quiet

# IP: d:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: d:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: d:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_99M_0/design_1_rst_ps8_0_99M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_99M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_99M_0/design_1_rst_ps8_0_99M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_99M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.gen/sources_1/bd/design_1/ip/design_1_riscv_soc_axi_wrapper_0_1/src/cpu.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_riscv_soc_axi_wrapper_0_1 || ORIG_REF_NAME==design_1_riscv_soc_axi_wrapper_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: d:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.gen/sources_1/bd/design_1/design_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1'. Do not add the DONT_TOUCH constraint.

# Block Designs: D:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.srcs/sources_1/bd/design_1/design_1.bd
# Block Designs: The module: 'design_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: D:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_99M_0/design_1_rst_ps8_0_99M_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_99M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_99M_0} -quiet] -quiet

# IP: D:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.srcs/sources_1/bd/design_1/ip/design_1_axi_interconnect_0_1/design_1_axi_interconnect_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_1 || ORIG_REF_NAME==design_1_axi_interconnect_0_1} -quiet] -quiet

# IP: D:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.srcs/sources_1/bd/design_1/ip/design_1_riscv_soc_axi_wrapper_0_1/design_1_riscv_soc_axi_wrapper_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_riscv_soc_axi_wrapper_0_1 || ORIG_REF_NAME==design_1_riscv_soc_axi_wrapper_0_1} -quiet] -quiet

# IP: d:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: d:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: d:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_99M_0/design_1_rst_ps8_0_99M_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_99M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_99M_0/design_1_rst_ps8_0_99M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_99M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.gen/sources_1/bd/design_1/ip/design_1_riscv_soc_axi_wrapper_0_1/src/cpu.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_riscv_soc_axi_wrapper_0_1 || ORIG_REF_NAME==design_1_riscv_soc_axi_wrapper_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: d:/Documents/FAU/NanoSat/riscv_radhart_coll/RiscVFSM/Riscvfsmwrapper/Riscvfsmwrapper.gen/sources_1/bd/design_1/design_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1'. Do not add the DONT_TOUCH constraint.
